version: '2'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ZMdkfqFU
      MYSQL_DATABASE: wp_niblog
      MYSQL_USER: niblog
      MYSQL_PASSWORD: gTmlrZADUtuk6pT7PsSr
    ports:
      - 3306:3306
  wordpress:
    image: wordpress:4.7.4-apache
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_PASSWORD: gTmlrZADUtuk6pT7PsSr
      WORDPRESS_DB_USER: niblog
      WORDPRESS_DB_NAME: wp_niblog
    depends_on:
      - mysql
    restart: always
